### ISSUE TITLE
Making "Related Content" skip you down to Docs/Downlds/Forms

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#35] opened 2016-08-26 19:50 UTC
Hey Jay,

Instead of having "Related Content" jump you to the bottom of the page, can we have one link called "Related Links" and one called "Documents/Downloads/Forms."  If both areas are being used on an office's page it would be great to have both links appear, but if an office just uses related links or just has documents/downloads/forms can we just have the utilized one appear in the nav?

Additional note about this - Right now if a page does NOT have subpages but DOES have populated "Related Links" and "Documents / Downloads / Forms" areas nothing appears in the right-navigation for that page. See President's Office page lack of right navigation screenshot below:

<img width="211" alt="screen shot 2018-01-08 at 2 26 41 pm" src="https://user-images.githubusercontent.com/14020234/34688406-04da3fb0-f480-11e7-8a7d-bc83bde62ef3.png">

and this page HAS populated "Related Links" and "Documents / Downloads / Forms" areas:

<img width="557" alt="screen shot 2018-01-08 at 2 36 08 pm" src="https://user-images.githubusercontent.com/14020234/34688806-5348a7bc-f481-11e7-857d-bcfd7a65c528.png">

If the above request to make individual links to skip you down the page to "Related Links" and to "Documents / Downloads / Forms" gets done - can pages like the President's Office have "Related Links" and "Documents / Downloads / Forms" display in the right navigation, despite not having other right navigation items.

Thanks,
Carrie

**Comment by rubillionaire** [comment] 2018-01-23 23:59
This change is now pushed to info.risd.systems. I've been using the Accounts Payable page as an working example, http://info.risd.systems/accounts-payable/

Let me know how it looks to you, @cmiller02.

**Comment by cmiller02** [comment] 2018-01-24 14:44
@rubillionaire - thanks so much for all the work you're doing.

Just a couple of things:

1) Can you change the name of the "Related Content" link to be "Related Links" instead
2) In terms of the functioning of the anchors, it seems like links "Payment Request" down through "Independent Contractor Exceptions" work well, with that section skipping up to the top of the page. Here are some examples with me grabbing screenshots that start at the top of the browser window:
![screen shot 2018-01-24 at 9 31 42 am](https://user-images.githubusercontent.com/14020234/35337901-60df71c4-00ea-11e8-9ec6-b1818cd111b7.png)
![screen shot 2018-01-24 at 9 31 55 am](https://user-images.githubusercontent.com/14020234/35337902-60f92f9c-00ea-11e8-99d5-e3c31963fa90.png)
![screen shot 2018-01-24 at 9 32 39 am](https://user-images.githubusercontent.com/14020234/35337904-611a9646-00ea-11e8-855c-8dbccbaa47dc.png)

but when you click on the "Performer and Speaker Payment Process" link that section doesn't go all the way to the top the way the others had:
![screen shot 2018-01-24 at 9 39 24 am](https://user-images.githubusercontent.com/14020234/35337971-a755f470-00ea-11e8-8ec9-18a7235ca6f0.png)

and then, clicking the "Related Content" link and the "Documents / Downloads / Forms" link doesn't seem to move the visual at all from the "Performer and Speaker Payment Process" result:
![screen shot 2018-01-24 at 9 33 47 am](https://user-images.githubusercontent.com/14020234/35338044-d5a7dd66-00ea-11e8-991f-01033ffb6d32.png)
![screen shot 2018-01-24 at 9 33 26 am](https://user-images.githubusercontent.com/14020234/35338045-d5b78004-00ea-11e8-9d06-9acfb9b666b9.png)

Can the anchors be set to always work the way the first three examples did? Thanks!

**Comment by rubillionaire** [comment] 2018-01-24 19:55
1. I've updated the `Related Content` links to say `Related Links`. The anchor has also been updated to match, `#related-links` instead of `#related-content`. While doing this I figured I would update the `Documents / Downloads / Forms` to be be more consistent as well. Its anchor is now `#documents-downloads-forms` instead of `#documents`.

2. The difference in how these anchors are functioning has to do with the length of the page, and its relative size compared to the size of your window. The issue is that with `Documents / Downloads / Forms` link for example is that clicking it will take you to the bottom of the page, and since there isn't more room to scroll, it can't align `Documents / Downloads / Forms`with the top of the window like it does when you click one of the other anchors. If you were to shrink the vertical height of your window, you might be able to get it to align. I think the crucial part of this feature is that it puts the request area within the view port of your window, making it easier to find. If you are interested, there is one thing I could do. This would be to add extra padding to the bottom of the page, empty space that could be used to allow the last item of the page to align with the top of the viewport. Let me know if you are interested in that!

**Comment by cmiller02** [comment] 2018-01-25 20:04
Thanks so much for the updates you made and the explanation - makes a ton of sense.
If it's not too much trouble, @rubillionaire, I'm interested in you adding the extra padding. Can we see how that might look/work? Thanks in advance!

**Comment by rubillionaire** [comment] 2018-01-31 02:21
@cmiller02 most definitely! I pushed a change the ensures that the last item in the main content rail is tall enough to have its top be completely scrolled into view. Let me know know how that looks!

http://info.risd.systems/accounts-payable/

**Comment by cmiller02** [comment] 2018-01-31 17:31
This looks perfect, @rubillionaire!  Think we're good to make this live. Thanks!

**Comment by rubillionaire** [comment] 2018-02-01 18:56
I am going to close this now that it is live on info.risd.edu.

**Comment by cmiller02** [comment] 2018-02-05 17:52
Hey @rubillionaire - so I think that this is working right in nearly all cases, but I noticed that there is the occasional page, like risd:store, that has subpage links but not "Related Links" or "Documents / Downloads / Forms" links that the padding isn't working on.  If you go to: http://info.risd.edu/risdstore/ and click "RISD Store Accounts" you'll see that the padding doesn't seem to be applied the way it was to "Related Links" or "Documents / Downloads / Forms." ("RISD Store Accounts" doesn't go to the top of the screen.) My apologies for not noticing this before - I'm thinking that pages that fit this mold are very very few - like maybe under 5 of them or something. Thanks!

**Comment by cmiller02** [comment] 2018-02-06 22:26
@rubillionaire - let me know if you want me to open a separate issue for this, but I'm noticing that pages like "Academic Advising" : http://info.risd.edu/academic-advising/ that have Related Links and Documents/Downloads/Forms we don't have "Related Links" and "Documents/Downloads/Forms" links on the right-hand side - presumably because this is a page without other sub-page links. So I think what's happening is that if there are no subpages and thus no sub-page links, then "Related Links" and "Documents/Downloads/Forms" links don't appear in the right-hand nav.

**Comment by rubillionaire** [comment] 2018-02-20 22:19
@cmiller02 I have updated the templates so that the "Related Links" & "Documents / Downloads / Forms" links always show up, not just in the context of a page that has "subpages".

I also updated the subpages templating a bit so that the full height fix, which we are using to ensure that the last elements in the main content are reachable by their links and can aligned to the top of the page when navigated to, also works in the context of a page that does not end in "Related Links" or "Documents / Downloads / Forms".

This should add a bit more consistency to everything. Let me know how it looks, and if there are any other cases I missed!

**Comment by cmiller02** [comment] 2018-02-21 15:53
Hey @rubillionaire - things are looking so great and working so well! Thanks so much! I literally went through the entire site and only found one tiny tiny thing - everything else looks perfect. To keep my brain straight I noted different types of pages (not an exhaustive list, but I think all that's needed for now). And literally every page on the site worked perfectly except for just one - which is a unique type of page:

http://info.risd.systems/parking/
(it's unique because it has no staff or right-hand contact info)
and so when you click on the first right-nav link, "Parking," it doesn't work the way the other anchors on the page do.

Anyway, I can't stress how minuscule this is, so if taking care of this will take a bunch of time or potentially mess other things up please don't work on it.

Categories of pages:

- http://info.risd.systems/academic-advising/: has RLs and DDFs (no subpages) and the right-hand nav links for them are visible and working well as anchors
- http://info.risd.systems/accounts-payable/: has RLs and DDFs and many subpages and the right-hand nav links for them all are visible and working well as anchors
- http://info.risd.systems/academic-affairs/: has RLs (no subpages) and the right-hand nav link for Related Links is visible and working well as an anchor
- http://info.risd.systems/beb-model-shop/: has DDFs (no subpages) and the right-hand nav link for Documents/Downloads/Forms is visible and working well as an anchor 
- http://info.risd.systems/mail-services/: has many subpages (no RLs or DDFs) and the right-hand nav links are all visible and working well as anchors

**Comment by rubillionaire** [comment] 2018-02-21 19:32
Thats great to hear, @cmiller02! Thank you for verifying the functionality throughout, you never know where you are going to find an edge case.

This particular edge case is due to the fact that the office name on each page has an anchor tag on it, so that you can link to that part of the page. In the case of the Parking page, that meant there were two anchors on the page for "#parking", and the first one was being used, instead of the second one. This would leave the user clicking the Parking link, and "jumping" them to the top of the page where the title of the office is.

Having the an anchor tag on the office name doesn't strike me as a useful link to have. Since the office name is the first thing on the page. And in the case where it can cause a unique ID collision like on the Parking page with the Parking section, I think its worth removing the anchor tag from the office name. I have done this on info.risd.systems, and now the Parking anchor works.

http://info.risd.systems/parking/#parking

Let me know if this trade off sounds worth while to you. I'd be happy to revert the change.

**Comment by cmiller02** [comment] 2018-02-22 14:05
I totally agree, @rubillionaire. Thank you for removing the anchor tag from the office name - and now things work great! I'd say we're totally set on this.

**Comment by rubillionaire** [comment] 2018-02-22 17:24
excellent, @cmiller02. The change is now live on info.risd.edu as well!

http://info.risd.edu/parking/#parking

**Closed by rubillionaire** 2018-02-22 17:24 UTC
